set_property SRC_FILE_INFO {cfile:/home/steven/Dropbox/Verilog/Labs/Lab4/Lab4.srcs/constrs_1/new/Lab4Const.xdc rfile:../../../Lab4.srcs/constrs_1/new/Lab4Const.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {led}]
