webtalk_init -webtalk_dir /home/steven/Dropbox/Verilog/Homework/Assignment4/Problem4/Problem4.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jan 28 13:20:30 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2015.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1412921" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211131974_0_0_121" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "12a7642d-b01b-4d5f-bf30-06b0400ae3b9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5df36b4d-df59-4155-9958-09953c482cc2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "ManjaroLinux" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Manjaro Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1529.882 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "ManjaroLinux" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Manjaro Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2900.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key chain -value "0362D093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "10:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Digilent/Basys3/15000000:" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Digilent/Basys3/15000000:Digilent/Basys3/15000000:" -context "labtool\\usage"
webtalk_transmit -clientid 1353925320 -regid "211131974_0_0_121" -xml /home/steven/Dropbox/Verilog/Homework/Assignment4/Problem4/Problem4.hw/webtalk/usage_statistics_ext_labtool.xml -html /home/steven/Dropbox/Verilog/Homework/Assignment4/Problem4/Problem4.hw/webtalk/usage_statistics_ext_labtool.html -wdm /home/steven/Dropbox/Verilog/Homework/Assignment4/Problem4/Problem4.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
