# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/steven/Dropbox/Verilog/Examples/Comparitor/Comparitor.cache/wt [current_project]
set_property parent.project_path /home/steven/Dropbox/Verilog/Examples/Comparitor/Comparitor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /home/steven/Dropbox/Verilog/Examples/Comparitor/Comparitor.srcs/sources_1/new/CompareSlice.v
  /home/steven/Dropbox/Verilog/Examples/Comparitor/Comparitor.srcs/sources_1/new/Compare.v
}
synth_design -top Compare -part xc7a35tcpg236-1
write_checkpoint -noxdef Compare.dcp
catch { report_utilization -file Compare_utilization_synth.rpt -pb Compare_utilization_synth.pb }
