# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/steven/Dropbox/Vivado/Lab1/Lab1.cache/wt [current_project]
set_property parent.project_path /home/steven/Dropbox/Vivado/Lab1/Lab1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib /home/steven/Dropbox/Vivado/Lab1/Lab1.srcs/sources_1/new/LabModule.v
read_xdc /home/steven/Dropbox/Vivado/Lab1/Lab1.srcs/constrs_1/new/Lab1Const.xdc
set_property used_in_implementation false [get_files /home/steven/Dropbox/Vivado/Lab1/Lab1.srcs/constrs_1/new/Lab1Const.xdc]

synth_design -top Lab1Module -part xc7a35tcpg236-1
write_checkpoint -noxdef Lab1Module.dcp
catch { report_utilization -file Lab1Module_utilization_synth.rpt -pb Lab1Module_utilization_synth.pb }
